package com.plath.scancard.data.ml

import android.net.Uri
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.text.TextRecognition
import com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

/**
 * IMP-10 10-1 Audit results (2026-08-23) — Comparison with camerax/SKILL.md threading / modern-apis / mlkit-spatial
 *
 * [Threading] Improvement required (non-destructive comments only):
 *   - InputImage.fromFilePath(context, uri) calls ContentResolver.openInputStream internally, causing
 *     blocking I/O. Currently depends on caller Dispatcher (ScanDocumentUseCase.processScannedPages
 *     runs on viewModelScope=Main). I/O on Main thread poses ANR risk. Wrapping with withContext(Dispatchers.IO)
 *     is recommended. However, this audit does not modify it to avoid breaking the existing pipeline;
 *     kept as comments for future action.
 *     Reference: camerax/SKILL.md "Thread safety: Camera callbacks often run on background executors. Dispatch UI updates on main thread."
 *   - recognizer.process(image).await() is a Play Services Task -> coroutines-play-services' await();
 *     safe as it's a suspend function, although it returns callbacks to the Main thread internally.
 *   - Correction proposal (reflect this comment in code upon application):
 *     ```
 *     suspend fun recognizeText(imageUri: Uri): String = withContext(Dispatchers.IO) {
 *         val image = InputImage.fromFilePath(context, imageUri) // IO thread
 *         recognizer.process(image).await().text
 *     }
 *     ```
 *
 * [Escaping / Resource leak] Note:
 *   - recognizer is a singleton-like client generated by TextRecognition.getClient().
 *     Native resources might remain upon Activity recreation as close() is not implemented.
 *     Recommended: Manage with @ActivityRetainedScoped or Application Scope, and call
 *     recognizer.close() in onCleared / Application.onTerminate. Currently not Hilt Singleton
 *     equivalent; consider explicit scoping in the future.
 *   - InputImage is URI-based and doesn't hold internal Bitmap, so no close required (OK).
 *
 * [Immutability / Builder reassignment] OK:
 *   - JapaneseTextRecognizerOptions.Builder().build() correctly builds in a single call.
 *     Even if Builder setters are fluent and return new instances, this code has no reassignment
 *     omissions as it builds once. Principles followed, although not applicable to Viewport/Recorder
 *     patterns in camerax/references/immutability.md.
 *
 * [ML Kit Spatial / Rotation] Note:
 *   - InputImage.fromFilePath auto-corrects EXIF rotation, but when using CameraX ImageProxy,
 *     MlKitAnalyzer auto-handles coordinate mapping/rotation/mirroring (recommended in modern-apis.md).
 *     Replace with MlKitAnalyzer and abolish manual ByteBuffer operations when migrating to
 *     CameraX ImageAnalysis in the future. Rotation is handled by the OS via current URI-based
 *     (JPEG) approach, so it's OK.
 *
 * [Thermal] N/A Not directly related. OCR itself is CPU-heavy; falls under docs/camera-thermals.md's
 *   "Mild tier: Stop background analysis" — consider OCR resolution downgrade (1080p->720p) upon heating.
 */
class TextRecognitionManager @Inject constructor(
    @param:ApplicationContext private val context: Context,
) {
    private val recognizer = TextRecognition.getClient(JapaneseTextRecognizerOptions.Builder().build())

    suspend fun recognizeText(imageUri: Uri): String {
        // AUDIT NOTE: Ideally should be wrapped in Dispatchers.IO due to blocking I/O (see KDoc above).
        // Kept as is for now to avoid affecting existing callers. Add withContext(Dispatchers.IO) when fixing.
        val image = InputImage.fromFilePath(context, imageUri)
        val result = recognizer.process(image).await()
        return result.text
    }

    // AUDIT NOTE: Future resource leak countermeasure — activate the following when calling close() in ApplicationScope:
    // fun close() { recognizer.close() }
}
